Repository netlify/edge-bundler, pull requests merged in 2022-05, with the labels that each got.

#7 feat: allow certificate to be supplied to `serve`
  src/server/server.ts
Labels: type: feature

#19 chore: add release-please action
  .github/workflows/release-please.yml
Labels: type: chore

#21 feat: update bootstrap to 6270f39aacac8b000a2f84f4
  deno/bundle.ts
  src/formats/javascript.ts
Labels: type: feature

#22 feat: add trailing slash to regular expressions
  src/manifest.ts
  test/manifest.ts
Labels: type: feature

#25 chore: mocks download of Deno CLI in test suite
  package-lock.json
  package.json
  test/main.ts
Labels: type: chore

#26 chore: set up Deno in release-please workflow
  .github/workflows/release-please.yml
Labels: type: chore, automerge

#27 chore: update package metadata
  package.json
Labels: type: chore, automerge

#30 Update CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore, automerge

#32 Update bootstrap to ef-bootstrap@527a33
  deno/bundle.ts
  src/formats/javascript.ts
Labels: type: feature
