Repository netlify/edge-bundler, pull requests merged in 2022-12, with the labels that each got.

#235 feat: save import map URL to manifest
  deno/lib/stage2.ts
  node/bundle.ts
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/formats/eszip.ts
  node/import_map.test.ts
  node/import_map.ts
  node/manifest.ts
  package-lock.json
  package.json
  shared/consts.ts
  test/fixtures/with_config/.netlify/edge-functions/import_map.json
  test/fixtures/with_config/helper.ts
  test/fixtures/with_import_maps/functions/func1.ts
  test/fixtures/with_import_maps/functions/import_map.json
  test/fixtures/with_import_maps/helper.ts
  test/integration/test.js
  test/util.ts
Labels: type: feature, automerge

#241 fix: correct import_map attribute name in validation
  node/bundler.test.ts
  node/validation/manifest/__snapshots__/index.test.ts.snap
  node/validation/manifest/index.test.ts
  node/validation/manifest/schema.ts
Labels: type: bug

#243 fix: add guard for import map with extraneous dist directory
  node/bundler.test.ts
  node/formats/eszip.ts
Labels: type: bug, automerge

#246 feat: use `netlify:import-map` specifier
  deno/bundle.ts
  deno/lib/stage2.ts
  node/bundle.ts
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/formats/eszip.ts
  node/import_map.test.ts
  node/import_map.ts
  node/manifest.ts
  node/server/server.ts
  shared/consts.ts
  shared/stage2.ts
  test/fixtures/with_import_maps/functions/func1.ts
  test/fixtures/with_import_maps/functions/import_map.json
  test/fixtures/with_import_maps/helper.ts
  test/util.ts
Labels: type: feature

#253 fix: do not transform paths when writing import map to disk
  node/import_map.test.ts
  node/import_map.ts
Labels: type: bug

#256 feat!: add support for user-defined import maps
  .eslintrc.cjs
  node/bundler.test.ts
  node/bundler.ts
  node/deno_config.test.ts
  node/deno_config.ts
  node/server/server.test.ts
  node/server/server.ts
  package-lock.json
  package.json
  test/fixtures/serve_test/.netlify/edge-functions/greet.ts
  test/fixtures/serve_test/.netlify/edge-functions/import_map.json
  test/fixtures/serve_test/deno.json
  test/fixtures/serve_test/helper.ts
  test/fixtures/serve_test/import_map.json
  test/fixtures/serve_test/netlify/edge-functions/echo_env.ts
  test/fixtures/with_import_maps/deno.json
  test/fixtures/with_import_maps/import_map.json
  test/fixtures/with_import_maps/user-functions/func2.ts
Labels: type: feature

#258 feat: read Deno config behind feature flag
  node/bundler.test.ts
  node/bundler.ts
  node/feature_flags.ts
Labels: type: feature

#259 feat: add system logging for Deno config file
  node/bundler.ts
  node/deno_config.test.ts
  node/deno_config.ts
  node/server/server.ts
Labels: type: feature

#265 feat!: add `importMapPaths` to `bundle` and `serve`
  node/bundler.test.ts
  node/bundler.ts
  node/deno_config.test.ts
  node/deno_config.ts
  node/deploy_config.test.ts
  node/deploy_config.ts
  node/feature_flags.ts
  node/import_map.ts
  node/server/server.test.ts
  node/server/server.ts
  test/fixtures/serve_test/deno.json
  test/fixtures/serve_test/import_map.json
  test/fixtures/serve_test/netlify/edge-functions/import-map.json
  test/fixtures/with_import_maps/deno.json
  test/fixtures/with_import_maps/helper2.ts
  test/fixtures/with_import_maps/import_map.json
  test/fixtures/with_import_maps/user-functions/func3/func3.ts
  test/fixtures/with_import_maps/user-functions/import_map.json
  test/util.ts
Labels: type: feature

#268 fix: read other import map paths when one doesn't exist
  node/bundler.test.ts
  node/import_map.ts
  test/util.ts
Labels: type: bug

#261 feat: add support for negative patterns
  node/bundler.test.ts
  node/declaration.test.ts
  node/declaration.ts
  node/manifest.test.ts
  node/manifest.ts
  test/fixtures/with_deploy_config/.netlify/edge-functions/config.json
Labels: type: feature, automerge

#271 fix: print nice npm error message for npm: specifier as well
  node/bundler.test.ts
  node/npm_import_error.ts
  test/fixtures/imports_npm_module_scheme/functions/func1.ts
Labels: type: bug, first responder

#273 feat!: make `config` export a plain object
  deno/config.ts
  node/config.test.ts
  node/config.ts
  test/fixtures/serve_test/netlify/edge-functions/echo_env.ts
  test/fixtures/with_config/.netlify/edge-functions/framework-func1.ts
  test/fixtures/with_config/netlify/edge-functions/user-func1.ts
  test/fixtures/with_config/netlify/edge-functions/user-func3.ts
  test/fixtures/with_config/netlify/edge-functions/user-func4.ts
Labels: type: feature
