Repository netlify/edge-bundler, pull requests merged in 2022-08, with the labels that each got.

#85 feat: add support for system logger
  src/bridge.ts
  src/bundler.ts
  src/logger.ts
  src/server/server.ts
  src/types.ts
  test/logger.ts
  test/main.ts
  test/types.ts
Labels: type: feature

#89 feat: use default logger in DenoBridge
  src/bridge.ts
  test/main.ts
Labels: type: feature

#82 feat: allow setting environment variables and disable extending in DenoServer
  src/bridge.ts
  src/server/server.ts
  test/bridge.ts
  test/main.ts
Labels: type: feature, automerge

#84 feat: update bootstrap url
  deno/bundle.ts
  src/formats/javascript.ts
Labels: type: chore, type: feature

#93 fix: ensure PATH is always set
  package-lock.json
  package.json
  src/bridge.ts
Labels: type: bug

#101 chore: fix tests with environment variables
  test/bridge.ts
Labels: type: chore

#100 fix: implement retries for Deno CLI download and additional logging
  package-lock.json
  package.json
  src/bridge.ts
  src/downloader.ts
Labels: type: bug

#102 feat: inline stage 2 ESZIP bundler
  deno/bundle.ts
  deno/lib/common.ts
  deno/lib/consts.ts
  deno/lib/stage2.ts
Labels: type: feature

#104 fix: fix deno download retry logic
  src/downloader.ts
  test/downloader.ts
  test/fixtures/deno.win.zip
  test/fixtures/deno.zip
Labels: type: bug
