Repository netlify/edge-bundler, pull requests merged in 2022-06, with the labels that each got.

#41 chore: add flag to disable code gen from strings
  src/server/server.ts
Labels: type: chore

#44 chore: deploy id automation
  .github/workflows/update-bootstrap-deploy-id.yml
Labels: type: chore

#50 feat: remove feature flag eszip
  src/bundler.ts
  test/bundler.ts
Labels: type: feature

#49 feat: bump edge bootstrap to 1.0.0
  deno/bundle.ts
  src/formats/javascript.ts
Labels: type: feature

#53 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type: chore

#48 feat: return generated manifest object
  src/bundler.ts
  src/manifest.ts
  test/bundler.ts
Labels: type: feature

#56 fix: await lifecycle hooks as they might return promises
  src/bridge.ts
Labels: type: bug
