Repository netlify/edge-bundler, pull requests merged in 2022-10, with the labels that each got.

#144 fix: use `allow-net` flag to run `config` function
  deno/config.ts
  node/config.ts
Labels: type: bug

#146 feat: update bootstrap latest to use latest version of bootstrap
  node/formats/javascript.ts
Labels: type: feature

#140 feat: allow display name in manifest
  node/declaration.ts
  node/manifest.test.ts
  node/manifest.ts
Labels: type: feature, automerge

#149 feat: Update bootstrap url to latest version
  node/formats/javascript.ts
Labels: type: feature

#141 feat: vendor eszip Deno module
  deno/lib/common.ts
  deno/vendor/deno.land/std@0.127.0/_util/assert.ts
  deno/vendor/deno.land/std@0.127.0/_util/os.ts
  deno/vendor/deno.land/std@0.127.0/path/_constants.ts
  deno/vendor/deno.land/std@0.127.0/path/_interface.ts
  deno/vendor/deno.land/std@0.127.0/path/_util.ts
  deno/vendor/deno.land/std@0.127.0/path/common.ts
  deno/vendor/deno.land/std@0.127.0/path/glob.ts
  deno/vendor/deno.land/std@0.127.0/path/mod.ts
  deno/vendor/deno.land/std@0.127.0/path/posix.ts
  deno/vendor/deno.land/std@0.127.0/path/separator.ts
  deno/vendor/deno.land/std@0.127.0/path/win32.ts
  deno/vendor/deno.land/std@0.98.0/async/deferred.ts
  deno/vendor/deno.land/std@0.98.0/async/delay.ts
  deno/vendor/deno.land/std@0.98.0/async/mod.ts
  deno/vendor/deno.land/std@0.98.0/async/mux_async_iterator.ts
  deno/vendor/deno.land/std@0.98.0/async/pool.ts
  deno/vendor/deno.land/std@0.98.0/async/tee.ts
  deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js
  deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm_bg.wasm
  deno/vendor/deno.land/x/eszip@v0.28.0/loader.ts
  deno/vendor/deno.land/x/eszip@v0.28.0/mod.ts
  deno/vendor/deno.land/x/retry@v2.0.0/deps.ts
  deno/vendor/deno.land/x/retry@v2.0.0/misc.ts
  deno/vendor/deno.land/x/retry@v2.0.0/mod.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/decorator.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/options.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/retry.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/tooManyTries.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/options.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/tools.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilDefined/decorators.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilDefined/retry.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilResponse/decorators.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilResponse/retry.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilTruthy/decorators.ts
  deno/vendor/deno.land/x/retry@v2.0.0/retry/utils/untilTruthy/retry.ts
  deno/vendor/deno.land/x/retry@v2.0.0/wait/decorators.ts
  deno/vendor/deno.land/x/retry@v2.0.0/wait/options.ts
  deno/vendor/deno.land/x/retry@v2.0.0/wait/timeoutError.ts
  deno/vendor/deno.land/x/retry@v2.0.0/wait/wait.ts
  deno/vendor/import_map.json
  node/bundler.test.ts
  node/bundler.ts
  node/feature_flags.ts
  node/formats/eszip.ts
  package-lock.json
Labels: type: feature

#161 feat: support JSX and TSX in edge functions
  node/finder.ts
Labels: type: feature, automerge

#166 fix: use import maps in config evaluation
  .eslintrc.cjs
  node/bundler.ts
  node/config.test.ts
  node/config.ts
  test/fixtures/with_config/.netlify/edge-functions/framework-func1.ts
  test/fixtures/with_config/.netlify/edge-functions/framework-func2.ts
  test/fixtures/with_config/netlify/edge-functions/user-func1.ts
  test/fixtures/with_config/netlify/edge-functions/user-func2.ts
Labels: type: bug

#165 feat: add support for post-cache routes
  node/config.test.ts
  node/config.ts
  node/declaration.ts
  node/manifest.test.ts
  node/manifest.ts
  test/fixtures/with_config/netlify/edge-functions/user-func3.ts
  test/fixtures/with_config/netlify/edge-functions/user-func4.ts
Labels: type: feature

#174 fix: run `config` export with `--allow-env`
  node/config.ts
  test/fixtures/with_config/netlify/edge-functions/user-func1.ts
Labels: type: bug

#175 feat: get config in server mode
  node/server/server.test.ts
  node/server/server.ts
  node/serving.test.ts
  test/fixtures/serve_test/echo_env.ts
Labels: type: feature
