Repository netlify/edge-bundler, pull requests merged in 2022-07, with the labels that each got.

#66 feat: refresh types on Deno CLI cache
  .eslintrc.cjs
  src/bridge.ts
  src/bundler.ts
  src/server/server.ts
  src/types.ts
  test/types.ts
Labels: type: feature, automerge

#71 chore: Update CODEOWNERS file
  .github/CODEOWNERS
Labels: type: chore

#72 feat: add support for import maps when bundling ESZIP
  .eslintrc.cjs
  .github/workflows/update-bootstrap-deploy-id.yml
  deno/bundle.ts
  src/bridge.ts
  src/bundler.ts
  src/formats/eszip.ts
  src/formats/javascript.ts
  src/import_map.ts
  src/types.ts
  test/bundler.ts
  test/fixtures/helper.ts
  test/fixtures/project_1/functions/func1.ts
Labels: type: feature, automerge

#76 feat: accept `basePath` parameter
  src/bundler.ts
  test/bundler.ts
  test/fixtures/helper.ts
  test/fixtures/project_1/functions/func1.ts
Labels: type: feature, automerge

#80 feat: add support for `denoDir` parameter
  src/bridge.ts
  src/bundler.ts
  src/feature_flags.ts
  test/bundler.ts
Labels: type: feature
