Repository netlify/edge-bundler, pull requests merged in 2022-11, with the labels that each got.

#177 fix: remove disallow-code-generation-from-strings flag
  node/server/server.ts
Labels: automerge

#190 feat!: replace `mode` property with `cache`
  .eslintrc.cjs
  node/config.ts
  node/declaration.ts
  node/manifest.test.ts
  node/manifest.ts
  test/fixtures/with_config/netlify/edge-functions/user-func3.ts
  test/fixtures/with_config/netlify/edge-functions/user-func4.ts
Labels: type: feature

#193 fix: log when module loading fails after max tries
  deno/lib/common.ts
Labels: type: bug

#196 fix: update to newer version of bootstrap: 636e17c6f5c1ed0008150054
  node/formats/javascript.ts
Labels: type: bug

#198 feat: add support for custom layers
  node/bundler.ts
  node/layer.ts
  node/manifest.test.ts
  node/manifest.ts
Labels: type: feature

#202 fix: update bootstrap to 63760359c1267a000900d7fb
  node/formats/javascript.ts
Labels: type: feature

#201 feat: add `layer:` prefix to ESZIP loader
  deno/lib/consts.ts
  deno/lib/stage2.ts
  node/bundler.test.ts
  node/bundler.ts
  test/fixtures/with_layers/functions/func1.ts
Labels: type: feature

#195 feat: add detection + nice error message for npm import errors
  node/bundle_error.ts
  node/bundler.test.ts
  node/formats/eszip.ts
  node/formats/javascript.ts
  node/npm_import_error.ts
  test/fixtures/imports_npm_module/functions/func1.ts
Labels: type: feature, automerge

#205 fix: update bootstrap to 63778906fc17350009bf07c4
  node/formats/javascript.ts
Labels: type: bug

#208 feat: add manifest validation
  .eslintrc.cjs
  node/bundle.ts
  node/formats/eszip.ts
  node/formats/javascript.ts
  node/index.ts
  node/manifest.test.ts
  node/validation/manifest/__snapshots__/index.test.ts.snap
  node/validation/manifest/error.ts
  node/validation/manifest/index.test.ts
  node/validation/manifest/index.ts
  node/validation/manifest/schema.ts
  package-lock.json
  package.json
Labels: automerge

#215 fix: update bootstrap to 637b7052e167bb00082f54f1
  node/formats/javascript.ts
Labels: type: feature, automerge

#217 fix: update bootstrap to 637cf7ce9214b300099b3aa8
  node/formats/javascript.ts
Labels: type: chore

#219 feat!: move internal config file to Edge Bundler
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/declaration.test.ts
  node/declaration.ts
  node/deploy_config.test.ts
  node/deploy_config.ts
  node/import_map.ts
  node/server/server.ts
  node/utils/error.ts
  test/fixtures/with_config/.netlify/edge-functions/config.json
  test/fixtures/with_config/.netlify/edge-functions/import_map.json
  test/fixtures/with_deploy_config/.netlify/edge-functions/config.json
  test/fixtures/with_deploy_config/.netlify/edge-functions/func2.ts
  test/fixtures/with_deploy_config/.netlify/edge-functions/import_map.json
  test/fixtures/with_deploy_config/netlify/edge-functions/func1.ts
  test/fixtures/with_deploy_config/util.ts
  test/fixtures/with_import_maps/functions/config.json
  test/fixtures/with_import_maps/functions/import_map.json
  test/fixtures/with_layers/functions/config.json
Labels: type: feature, automerge

#224 feat!: remove support for JavaScript bundles
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/feature_flags.ts
  node/formats/javascript.ts
  node/server/server.ts
  test/fixtures/invalid_functions/functions/func1.ts
  test/integration/test.js
Labels: type: feature

#225 feat: mark custom layers as `externals`
  deno/bundle.ts
  deno/lib/consts.ts
  deno/lib/stage2.ts
  node/bundler.test.ts
  node/bundler.ts
  node/formats/eszip.ts
  shared/stage2.ts
  test/fixtures/with_layers/functions/config.json
Labels: type: feature
