Repository netlify/edge-bundler, pull requests merged in 2022-09, with the labels that each got.

#109 feat: add support for import maps with ESZIP
  common/stage2.ts
  deno/bundle.ts
  deno/lib/stage2.ts
  package-lock.json
  package.json
  src/formats/eszip.ts
  src/import_map.ts
  test/bundler.ts
  test/import_map.ts
Labels: type: feature, automerge

#113 fix: move `stage2.ts` to `src`
  deno/lib/stage2.ts
  src/formats/eszip.ts
  src/stage2.ts
Labels: type: bug

#117 fix: create `shared` directory
  deno/lib/stage2.ts
  node/bridge.ts
  node/bundle.ts
  node/bundle_error.ts
  node/bundler.ts
  node/declaration.ts
  node/downloader.ts
  node/edge_function.ts
  node/feature_flags.ts
  node/finder.ts
  node/formats/eszip.ts
  node/formats/javascript.ts
  node/home_path.ts
  node/import_map.ts
  node/index.ts
  node/logger.ts
  node/manifest.ts
  node/package_json.ts
  node/platform.ts
  node/server/server.ts
  node/server/util.ts
  node/types.ts
  node/utils/non_nullable.ts
  node/utils/sha256.ts
  package.json
  shared/stage2.ts
  test/bootstrap.ts
  test/bridge.ts
  test/bundler.ts
  test/downloader.ts
  test/import_map.ts
  test/logger.ts
  test/main.ts
  test/manifest.ts
  test/types.ts
  tsconfig.json
Labels: type: bug

#118 fix: fix `getPackageVersion`
  node/package_json.ts
  package-lock.json
  package.json
  test/package_json.ts
Labels: type: bug, automerge

#120 fix: use right location for Deno bundler
  node/formats/eszip.ts
  node/package_json.ts
Labels: type: bug, automerge

#123 fix: convert file URL to path
  node/package_json.ts
Labels: type: bug, automerge

#122 feat: export `metadata` object in stage 2
  .eslintrc.cjs
  deno/lib/stage2.ts
  package.json
  test/deno/stage2.test.ts
  test/node/bootstrap.ts
  test/node/bridge.ts
  test/node/bundler.ts
  test/node/downloader.ts
  test/node/fixtures/deno.win.zip
  test/node/fixtures/deno.zip
  test/node/fixtures/helper.ts
  test/node/fixtures/invalid_functions/functions/func1.ts
  test/node/fixtures/project_1/functions/func1.ts
  test/node/import_map.ts
  test/node/logger.ts
  test/node/main.ts
  test/node/manifest.ts
  test/node/types.ts
Labels: type: feature, automerge

#126 feat: export `metadata` object in local stage 2
  node/formats/javascript.ts
  test/node/stage_2.ts
Labels: type: feature

#129 feat: add `functions` level to `metadata` object
  deno/lib/stage2.ts
  node/formats/javascript.ts
  package.json
  test/deno/stage2.test.ts
  test/node/stage_2.ts
Labels: type: feature

#128 fix: run `deno` with `--no-config`
  node/formats/eszip.ts
  node/formats/javascript.ts
  node/server/server.ts
  test/node/bundler.ts
  test/node/stage_2.ts
Labels: type: bug, automerge

#116 feat: add tests for `serve` functionality
  node/server/server.ts
  package-lock.json
  package.json
  test/node/fixtures/serve_test/echo_env.ts
  test/node/serving.ts
Labels: type: chore

#139 chore: replace AVA with Vitest
  .eslintrc.cjs
  .github/workflows/integration.yml
  .github/workflows/workflow.yml
  deno/lib/stage2.test.ts
  node/bootstrap.test.ts
  node/bridge.test.ts
  node/bundler.test.ts
  node/downloader.test.ts
  node/import_map.test.ts
  node/logger.test.ts
  node/main.test.ts
  node/manifest.test.ts
  node/package_json.test.ts
  node/serving.test.ts
  node/stage_2.test.ts
  node/types.test.ts
  package-lock.json
  package.json
  test/fixtures/deno.win.zip
  test/fixtures/deno.zip
  test/fixtures/helper.ts
  test/fixtures/invalid_functions/functions/func1.ts
  test/fixtures/project_1/functions/func1.ts
  test/fixtures/serve_test/echo_env.ts
  test/integration/functions/func1.ts
  test/integration/test.js
  test/package_json.ts
  test/util.ts
  vitest.config.ts
Labels: type: chore

#133 feat: add support for `config` export
  .eslintrc.cjs
  .github/workflows/integration.yml
  deno/config.ts
  node/bridge.ts
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/config.ts
  node/declaration.ts
  node/downloader.test.ts
  node/feature_flags.ts
  node/types.test.ts
  test/fixtures/with_config/.netlify/edge-functions/framework-func1.ts
  test/fixtures/with_config/.netlify/edge-functions/framework-func2.ts
  test/fixtures/with_config/netlify/edge-functions/user-func1.ts
  test/fixtures/with_config/netlify/edge-functions/user-func2.ts
  test/fixtures/with_import_maps/functions/func1.ts
  test/util.ts
Labels: type: feature

#143 chore: fix version lookup in integration test
  test/integration/test.js
Labels: type: chore
