Repository netlify/edge-bundler, pull requests merged in 2023-03, with the labels that each got.

#303 feat: update bootstrap version
  node/formats/javascript.ts
Labels: automerge

#320 chore: clean some default feature flags
  node/bundler.test.ts
  node/bundler.ts
  node/config.test.ts
  node/feature_flags.ts
Labels: type: chore

#312 feat: populate generator field if edge function is from a config file
  node/bundler.test.ts
  node/bundler.ts
  node/deploy_config.test.ts
  package-lock.json
  package.json
  test/fixtures/with_deploy_config/.netlify/edge-functions/func3.ts
  test/fixtures/with_deploy_config/.netlify/edge-functions/manifest.json
Labels: type: feature

#325 chore: cleanup
  .eslintrc.cjs
  node/bridge.test.ts
  node/deploy_config.ts
  node/downloader.test.ts
  node/main.test.ts
  node/manifest.ts
  node/types.test.ts
  node/validation/manifest/index.test.ts
  node/validation/manifest/index.ts
  package-lock.json
  package.json
  renovate.json5
  vitest.config.ts
Labels: automerge

#336 chore: fix typo
  node/formats/javascript.ts
Labels: automerge

#322 chore: update vitest and test with node 14.18.0 as minimum
  .github/workflows/workflow.yml
  node/validation/manifest/__snapshots__/index.test.ts.snap
  package-lock.json
  package.json
  vitest.config.ts
Labels: automerge

#349 chore: improve speed of downloader test
  node/downloader.test.ts
  package-lock.json
  package.json
Labels: automerge
